version: '3.8
services:
  neo4j:
    image: neo4j:5.10
    container_name: projetoNeo4j
    ports: 
      - "7474:7474" #HTTP Browser
      - "7687:7687" #Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/root # autenticação básica
    volumes:
      - ./data/data # persiste dados em ./data local